name: nubi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  bloc: ^8.1.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  google_fonts: ^4.0.3
  url_launcher: ^6.1.11
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
